services:
  idp:
    ports:
      - 443:8443
    image: keycloak/keycloak:25.0
    environment:
      # KC_LOG_LEVEL: info,org.keycloak.authentication:trace
      KEYCLOAK_ADMIN: user
      KEYCLOAK_ADMIN_PASSWORD: bitnami
      KC_DB: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_HOST: db
      KC_DB_URL_DATABASE: bitnami_keycloak
      KC_DB_PASSWORD: password
      KC_DB_USERNAME: bn_keycloak
      KC_HTTP_ENABLED: false
      KC_HOSTNAME_STRICT: false
      KC_HTTPS_CLIENT_AUTH: request
      KC_HTTPS_KEY_STORE_FILE: /opt/keycloak/conf/keystores/keystore.p12
      KC_HTTPS_KEY_STORE_PASSWORD: 2345
      KC_HTTPS_TRUST_STORE_FILE:  /opt/keycloak/conf/truststores/truststore.p12 
      KC_HTTPS_TRUST_STORE_PASSWORD:  3456
    command:
      - "start-dev"
    volumes:
      - ./idp/keystores:/opt/keycloak/conf/keystores
      - ./idp/truststores:/opt/keycloak/conf/truststores
    depends_on:
      - db
      - smtp
  db:
    container_name: db
    image: postgres:16.3
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: bn_keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bitnami_keycloak
    volumes:
      - ./db/data:/var/lib/postgresql/data
  smtp:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025